#cloud-config
apt_update: true
apt_reboot_if_required: true
hostname: "${hostname}"
packages:
  - wget
  - software-properties-common
  - screen
  - links
  - rsyslog
  - acct
  - python3
  - python3-pip
  - snoopy
  # LAMP
  - apache2
  - mysql-server
  - php7.2
  - libapache2-mod-php7.2
  - php-mysql
  - php-curl
  - php-json
  - php-cgi

write_files:
  - path: /etc/sudoers.d/devon
    content: "devon ALL=(ALL) NOPASSWD: ALL"

  - path: /etc/sudoers.d/sudo
    content: "%sudo ALL=(ALL) NOPASSWD: ALL"

  - path: /etc/sudoers.d/admin
    content: "%admin ALL=(ALL) NOPASSWD: ALL"

  - path: /etc/profile.d/_snoopy.sh
    content: |-
      #!/bin/bash
      grep "libsnoopy.so" /etc/ld.so.preload 1>/dev/null 2>&1
      if [ $? -ne 0 ]; then
        export LD_PRELOAD="/lib/x86_64-linux-gnu/libsnoopy.so:$LD_PRELOAD"
      fi

users:
  - name: "devon"
    passwd: "!"
    shell: /bin/bash
    groups:
      - "sudo"
      - "admin"
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD4pxr8LWZGDw1lSKwN4geFQoWlWPUUCuDHxYQvOErSCSdEYeqCUVPO+DL5q2/O2uBbGaOnsmZYNcIBqcf7lleuSEsR7OpVMGk5CQbYAn5YF5gm0YzSBe2gUaQoq6888AjAVbLgBFhsn5tuz6iRe10AjcsfqjKuF7AbDtVz59kekYwiyEeeHS+3bk3892cB0F1rm53qRxkO7SdfGIJVNAZxp9NNmPK4zfB+dY4F5fYfBkOHhzy8roaeJWRsEQiB+4nLBJRADA5Athq+Oe/SW63H0qPn0yhA30IH0tXGZISrjuFfc5LF6D3MU8wiqt9ygkyKUnY2Mee+8xbDKazp5ott devon_starwar8"

bootcmd:
  - "apt-add-repository -y ppa:ansible/ansible"
  - "apt update"
  - "apt install -y ansible"
  - "mkdir -p /etc/ansible"
  - echo "localhost ansible_connection=local" > /etc/ansible/hosts




