---

- name: /etc/securetty
  copy:
    dest:  /etc/securetty
    owner: root
    group: root
    mode:  '0400'
    content: |+
      # list of terminals on which root is allowed to login
      console
      #
      # UART serial ports
      ttyS0
      ttyS1
      #
      vc/0
      vc/1
      vc/2
      vc/3
      vc/4
      vc/5
      vc/6
      vc/7
      vc/8
      vc/9
      vc/10
      vc/11
      #
      hvc0
      #
      # TTYs sorted by major number according to Documentation/devices.txt
      tty0
      tty1
      tty2
      tty3
      tty4
      tty5
      tty6
      tty7
      tty8
      tty9
      tty10
      tty11

