---

- name: disableipv6.conf
  copy:
    dest:  /etc/sysctl.d/disableipv6.conf
    owner: root
    group: root
    mode:  '0644'
    content: |+
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
      net.ipv6.conf.lo.disable_ipv6=1
      net.ipv6.conf.all.disable_ipv6=1


- name:    disableipv6-sysctl-p
  command: sysctl -p


