---

- name: /etc/security/opasswd
  file:
    path:  /etc/security/opasswd
    owner: root
    group: root
    mode:  '0600'

- name: Set PAM file permissions
  file:
    path:    /etc/pam.d
    owner:   root
    group:   root
    mode:    '0755'
    recurse: true
    state:   directory

