---

- name: Get user accounts
  command:      "awk -F: '{print $1}' /etc/passwd"
  changed_when: false
  check_mode:   false
  register:     users

- name: delete .exrc files from user homedirs
  file:
    dest:         '~{{ item }}/.exrc'
    state:        'absent'
  with_flattened: '{{ users.stdout_lines | default([]) }}'
